### ISSUE TITLE
Tcollector poll interval is hardcoded to 15 seconds

### ISSUE THREAD

**Issue by asadpiz** [OpenTSDB/tcollector#123]
Hello,

tcollector should invoke the scripts placed in "collectors" folder at the time specified by the directory in which they are placed e.g., a collector placed in directory "collectors/1/" should be invoked after every 1 second, a collector placed in "collectors/2/" should be invoked after every 2 seconds and so on.

But the tcollector version available at: git://github.com/OpenTSDB/tcollector.git

Invokes the scripts in the collectors folder after "15 seconds" regardless of the directory in which they are placed. 

<h2>To Reproduce the Issue:</h2>
I have created a directory in the collectors folder with name "1" and placed my collector inside this directory. But instead of spawning this collector every 1 second, it is spawned after 15 seconds. My /var/log/tcollector output:

2013-12-13 12:46:00,607 tcollector[10013] INFO: Loading __init__.py
2013-12-13 12:46:00,607 tcollector[10013] INFO: Loading mysqlconf.py
2013-12-13 12:46:00,607 tcollector[10013] INFO: Loading config.py
2013-12-13 12:46:00,608 tcollector[10013] INFO: Loading udp_bridge_conf.py
2013-12-13 12:46:00,609 tcollector[10013] INFO: SenderThread startup complete
2013-12-13 12:46:00,609 tcollector[10013] INFO: s.py (interval=1) needs to be spawned

<b>2013-12-13 12:46:00,611 tcollector[10013] INFO: spawned s.py (pid=10016)</b>

2013-12-13 12:46:02,105 tcollector[10013] INFO: Selected connection: 127.0.0.1:4242
2013-12-13 12:46:15,626 tcollector[10013] INFO: s.py (interval=1) needs to be spawned

<b>2013-12-13 12:46:15,629 tcollector[10013] INFO: spawned s.py (pid=10023)</b>

As you can see the script "s.py" is launched at 12:46:00 and then again at 12.46:15. These 15 seconds are consistent no matter what the script (this test script only has 1 print statement)

**Comment by johann8384** [comment]
I have updated the documentation to reflect what my testing shows, and what the code appears to be doing also. Please let me know if you have any objections to closing this issue based on the updated documentation.
@vasiliyk @asadpiz

**Comment by vasiliyk** [comment]
@johann8384 Please, wait with closing of the issue.

>>So collectors that fire up, do one thing, and then die, tend to work better.
I believe here we try to fix broken collectors and it is not job of tcollector.

**Comment by tsuna** [comment]
We could build a smarter way to know how much time to sleep until the next time we know we need to check/spawn a collector.  I don't think it's reasonable to expect everybody to use long-lived collectors (even though I agree they're better).  There are plenty of folks in the same situation as @johann8384.

Maybe we could have `spawn_children()` keep track of what is the min amount of time until the next collector needs to be spawned.  We have that `if' that checks `col.interval <= now - col.lastspawn` to see if we need to spawn a collector.  Maybe we can add an `else` clause that tracks the minimum value of `now - col.lastspawn` and returns that, so that `main_loop()` can sleep this amount of time (or 15s if the amount is 0).

Does that sound reasonable?

**Comment by johann8384** [comment]
@tsuna That sound very reasonable. I believe that would allow TCollector to work the way most people believe it already works.

**Comment by dominosly** [comment]
Hello - Just started using tcollector and noticed in docs that the shortest supported interval was 15 seconds, starting searching and came on this thread. Is the suggestion made by @tsuna actively being worked on? I have written a collector I'd ultimately like to run every second, along with the stock ifstat.py. Of course, I tried just decreasing the sleep interval in the modules, but the sleep specifications in the main loops in tcollector still force running every 15 seconds. Thanks in advance for any info.

**Comment by johann8384** [comment]
If you want something to report every second, then you'll want to place it
in the 0 folder and have it do "while true: stuff, sleep 1: loop"

**Comment by dominosly** [comment]
@johann8384 Thanks, I figured that out and it works as expected. Initially, I was just thrown of due to tcollectors dedpulication and mistook this for the samples not being written on a per second basis. Had to generate some load, then I finally figured out it was recording every second as expected.
