### ISSUE TITLE
Can't make out of the box

### ISSUE THREAD

**Issue by pragmb** [OpenTSDB/tcollector#201]
Hello guys,

I tried building the RPM, but it fails. The `make` command outputs an error linked to the `collectors/0/eos.py` file.

By removing the corresponding entry in the Makefile it seems to fix things, but it's a hack.
Do you have also have this problem? Thanks!

**Comment by vasiliyk** [comment]
Hello @hynd.
Could you help me with testing of RPM building with regard to the issue.

Thanks.

**Comment by hynd** [comment]
Hey,
Just gave it a try - the "make / make rpm" building is also broken for me (i use most of the same files, but not from the makefile-generated .spec).

The eos.py file is missing - maybe @tsuna has a copy he could add?

If it is made available, it would also get added to the non-EOS .rpm which might be unnecessary. To exclude it would need a little bit of juggling of the Makefile (since it's included at .dist-stamp).

**Comment by tsuna** [comment]
Argh, sorry I think I messed that up in one of my commits.  I want to resurrect this collector with a different code anyway.

**Comment by tsuna** [comment]
OK, I created PR #204 to resurrect this collector.  That should solve this issue.

**Comment by vasiliyk** [comment]
Fixed with pull request https://github.com/OpenTSDB/tcollector/pull/204. Thank you all.
