### ISSUE TITLE
How tcollector cooperates with RabbitMQ?

### ISSUE THREAD

**Issue by louzhenyu** [OpenTSDB/tcollector#205]
Dear all,
    I implemented a collector to get message from RabbitMQ. At first I choosed a long connection to RabbitMQ, but the collector didn't work. I had to fetch message one by one from RabbitMQ and print it in function main() in my collector once a time. Though it worked, but it hadn't give a real-time response to RabbitMQ. Could you please give some suggestion? Thanks!

**Comment by johann8384** [comment]
If you share your collector I might be able to assist, this may also be a better thing to post in the TCollector group rather than an issue, you  might get a wider audience there. 

It doesn't sound like there is an issue with TCollector here so I am closing this, feel free to re-open if I am mistakne.
