### ISSUE TITLE
TCollector will stop working September 2020

### ISSUE THREAD

**Issue by HariSekhon** [OpenTSDB/tcollector#405]
This isn't that far away, the  safety number in the following line of code should probably be increased to something a lot bigger before this breaks everyone's tcollector metrics:
```
MAX_REASONABLE_TIMESTAMP = 1600000000  # Good until September 2020 :)
```

Maybe something more like this:

```
MAX_REASONABLE_TIMESTAMP = 2209212000 # Good until Tue  3 Jan 14:00:00 GMT 2040
```
This will give everyone a chance to come back from Christmas / New Year break and be back around their desks when it breaks, if anybody is still using TCollector that far in the future and AI hasn't replaced all of our jobs by then....

**Comment by bysse** [comment]
Got burned by this yesterday. I'll never get those hours back again :)

**Comment by HariSekhon** [comment]
@bysse at least the answer and fix was just a search away... :)

**Comment by elfchief** [comment]
Since many/most people using tcollector are probably using the latest official tcollector release (1.3.2), which predates this patch, it wouldn't be surprising if most tcollector users are now experiencing this problem. You may consider getting 1.3.3 out the door ASAP, or doing a quick point release with just this change.

Oddly, this was harder for me to track down than it otherwise would have been, because I somehow *did* get one data point every hour or two, so my graphs weren't completely missing data -- the data was just very, *very* coarse (temporally speaking).

**Comment by bysse** [comment]
Yes, I should have included a search keyword like `Timestamp is too far out in the future` when posting my initial comment.
We have pretty large volumes so we were also getting disk alerts for `/var` and uncommitted journal alerts.

**Comment by johann8384** [comment]
Yes, you are right, I will try and get that done.

Adding the OpenTSDB list as well.

**Comment by mzw-g** [comment]
yes,i got it，our TCollector all down at 2020-09-13 ....
